import { IMAGES } from './images';

/**
 * 12 Comprehensive Clinical Treatment Specialties at ReliveCare
 * Strictly focused on common patient conditions: Knee pain, Back pain, Shoulder pain,
 * Neck pain, Joint pain, Sports injuries, Manual therapy, Post-op rehab, etc.
 */

export const TREATMENTS_DATA = [
  {
    id: "knee-pain",
    title: "Knee Pain & Rehabilitation",
    category: "Lower Extremity",
    tag: "High Demand",
    shortDesc: "Specialized therapy for osteoarthritis, meniscus recovery, patellofemoral pain, and knee joint stiffness.",
    fullDesc: "Our knee rehabilitation protocol combines gentle joint mobilization, patellar tracking correction, and targeted quadriceps/hamstring strengthening to reduce weight-bearing discomfort and restore walking confidence.",
    image: IMAGES?.treatments?.kneePain?.src || "https://images.unsplash.com/photo-1574680096145-d05b474e2155?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.kneePain?.alt || "Physiotherapist treating patient knee joint",
    conditions: [
      "Knee Osteoarthritis & joint stiffness",
      "Meniscus tears & cartilage irritation",
      "Patellar tracking dysfunction",
      "Ligament sprains (ACL/MCL recovery)",
    ],
    approaches: [
      "Patellofemoral joint mobilization",
      "VMO & quadriceps strengthening",
      "Closed-kinetic chain exercise therapy",
      "Gait & alignment correction",
    ],
  },
  {
    id: "back-pain",
    title: "Back & Spine Pain Relief",
    category: "Spine Care",
    tag: "Core Specialty",
    shortDesc: "Targeted physical therapy for lumbar strain, slip disc, sciatica, and chronic lower back stiffness.",
    fullDesc: "Spinal pain often results from biomechanical compensations, disc compression, or postural imbalances. We relieve neural irritation through spinal decompression, core stability exercises, and manual joint mobilization.",
    image: IMAGES?.treatments?.backPain?.src || "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.backPain?.alt || "Physiotherapist performing lumbar spine mobilization",
    conditions: [
      "Lumbar disc bulge / herniation",
      "Sciatica & radiating nerve discomfort",
      "Mechanical lower back pain & spasms",
      "Postural spinal strain",
    ],
    approaches: [
      "Spinal mobilization & decompression",
      "Deep core stabilizer activation",
      "Neural flossing & mobility drills",
      "Ergonomic postural guidance",
    ],
  },
  {
    id: "shoulder-pain",
    title: "Shoulder Pain & Mobility",
    category: "Upper Extremity",
    tag: "Mobility Care",
    shortDesc: "Targeted mobilization and strengthening for frozen shoulder, rotator cuff tendonitis, and impingement.",
    fullDesc: "Shoulder conditions can severely limit daily reaching and overhead tasks. Our phased approach gently restores lost capsular mobility before progressively reloading the rotator cuff and scapular musculature.",
    image: IMAGES?.treatments?.shoulderPain?.src || "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.shoulderPain?.alt || "Physical therapist mobilizing shoulder joint",
    conditions: [
      "Frozen Shoulder (Adhesive Capsulitis)",
      "Subacromial Impingement Syndrome",
      "Rotator Cuff Tendonitis",
      "Shoulder weakness & instability",
    ],
    approaches: [
      "Glenohumeral joint mobilization",
      "Scapular rhythm re-education",
      "Rotator cuff progressive resistive exercises",
      "Gentle end-range stretching",
    ],
  },
  {
    id: "neck-pain",
    title: "Neck & Cervical Pain",
    category: "Spine Care",
    tag: "Spine Focus",
    shortDesc: "Comprehensive therapy for cervical spondylosis, neck stiffness, trap spasms, and tech-neck strain.",
    fullDesc: "Modern desk work and cervical strain create chronic muscular tension and restricted vertebral motion. We combine manual cervical traction, deep neck flexor strengthening, and upper thoracic mobilization.",
    image: IMAGES?.treatments?.neckPain?.src || "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.neckPain?.alt || "Cervical spine physical therapy",
    conditions: [
      "Cervical spondylosis & disc wear",
      "Chronic neck stiffness & muscle spasms",
      "Forward head posture (Tech-neck)",
      "Tension headaches from upper cervical strain",
    ],
    approaches: [
      "Gentle cervical joint mobilization",
      "Deep cervical flexor training",
      "Upper trapezius myofascial release",
      "Workstation ergonomic advice",
    ],
  },
  {
    id: "joint-pain",
    title: "Joint Pain & Osteoarthritis",
    category: "Bone & Joint",
    tag: "Specialized Care",
    shortDesc: "Non-invasive rehabilitation for degenerative joint conditions, cartilage preservation, and joint mobility.",
    fullDesc: "Structured therapeutic exercise and manual techniques to alleviate joint friction, strengthen surrounding stabilizing muscles, reduce inflammation, and maintain functional independence.",
    image: IMAGES?.treatments?.jointPain?.src || "https://images.unsplash.com/photo-1597764690523-15bea4c581c9?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.jointPain?.alt || "Clinical joint mobilization therapy",
    conditions: [
      "Osteoarthritis (Hip, Knee, Spine)",
      "Generalized joint stiffness & morning pain",
      "Post-fracture joint stiffness",
      "Age-related degenerative joint wear",
    ],
    approaches: [
      "Joint decompression techniques",
      "Low-impact resistance therapy",
      "Range of motion optimization",
      "Functional movement re-education",
    ],
  },
  {
    id: "sports-injuries",
    title: "Sports Injury Rehabilitation",
    category: "Athletic Recovery",
    tag: "Active Recovery",
    shortDesc: "Phased rehabilitation for athletic sprains, muscle tears, tendonitis, and safe return to sport.",
    fullDesc: "From recreational players to dedicated athletes, our sports recovery protocols focus on tissue healing, proprioceptive retraining, and functional movement re-conditioning to ensure safe, confident recovery.",
    image: IMAGES?.treatments?.sportsInjuries?.src || "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.sportsInjuries?.alt || "Sports injury functional rehabilitation",
    conditions: [
      "Ligament sprains (Ankle, ACL, MCL)",
      "Muscle strains (Hamstring, Calf, Groin)",
      "Tennis elbow & Golfer's elbow",
      "Plantar fasciitis & Achilles tendonitis",
    ],
    approaches: [
      "Sport-specific movement retraining",
      "Eccentric loading protocols",
      "Neuromuscular control & balance drills",
      "Safe return-to-activity testing",
    ],
  },
  {
    id: "manual-therapy",
    title: "Manual Therapy & Mobilization",
    category: "Hands-On Care",
    tag: "Clinical Technique",
    shortDesc: "Hands-on joint mobilization, soft tissue release, and myofascial decompression for immediate pain relief.",
    fullDesc: "Precise hands-on clinical interventions performed by our physiotherapists to modulate pain, reduce intra-articular pressure, release deep muscular tension, and restore joint gliding mechanics.",
    image: IMAGES?.treatments?.manualTherapy?.src || "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.manualTherapy?.alt || "Hands-on clinical manual physical therapy",
    conditions: [
      "Restricted joint capsular movement",
      "Spinal facet joint locking",
      "Deep myofascial trigger points",
      "Chronic muscular guarding & tightness",
    ],
    approaches: [
      "Maitland & Mulligan joint mobilization",
      "Soft tissue mobilization & release",
      "Passive stretching & muscle energy techniques",
      "Instrument-assisted soft tissue therapy",
    ],
  },
  {
    id: "post-operative",
    title: "Post-Operative Rehabilitation",
    category: "Surgical Recovery",
    tag: "Structured Phases",
    shortDesc: "Staged rehabilitation following joint replacements (TKR, THR), arthroscopic surgeries, and fractures.",
    fullDesc: "Structured, surgeon-aligned recovery phases focusing on timely swelling reduction, scar tissue mobilization, safe progressive weight-bearing, and full restoration of daily functional autonomy.",
    image: IMAGES?.treatments?.postOperative?.src || "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.postOperative?.alt || "Post-operative orthopedic rehabilitation",
    conditions: [
      "Total Knee Replacement (TKR)",
      "Total Hip Replacement (THR)",
      "Arthroscopic ligament reconstruction",
      "Post-fracture ORIF & casting recovery",
    ],
    approaches: [
      "Phase-specific surgical protocol adherence",
      "Early passive-to-active movement",
      "Swelling management & gentle lymphatics",
      "Independent gait retraining",
    ],
  },
  {
    id: "neurological-rehab",
    title: "Neurological Rehabilitation",
    category: "Neuro Recovery",
    tag: "Motor Retraining",
    shortDesc: "Physical therapy for stroke recovery, facial palsy (Bell's palsy), balance deficits, and nerve injuries.",
    fullDesc: "Task-oriented physical therapy protocols leveraging neuromuscular re-education to improve limb coordination, muscle tone, balance confidence, and daily functional living.",
    image: IMAGES?.treatments?.neurological?.src || "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.neurological?.alt || "Neurological physical therapy",
    conditions: [
      "Post-stroke hemiparesis & walking support",
      "Bell's palsy & facial nerve recovery",
      "Balance deficits & gait ataxia",
      "Peripheral nerve injuries & foot drop",
    ],
    approaches: [
      "Task-oriented balance and gait training",
      "Sensory re-education & motor facilitation",
      "Functional transfer and independence drills",
      "Postural stability conditioning",
    ],
  },
  {
    id: "exercise-therapy",
    title: "Exercise Therapy & Conditioning",
    category: "Functional Training",
    tag: "Supervised Care",
    shortDesc: "Scientific exercise prescription focused on progressive loading, muscle balance, and functional stamina.",
    fullDesc: "Supervised therapeutic exercises designed to transition the patient from pain relief to physical vitality through tailored resistance, stability drills, and movement re-education.",
    image: IMAGES?.treatments?.exerciseTherapy?.src || "https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.exerciseTherapy?.alt || "Supervised exercise therapy",
    conditions: [
      "General muscular deconditioning",
      "Post-injury weakness & muscle loss",
      "Poor physical endurance & fatigue",
      "Functional movement imbalances",
    ],
    approaches: [
      "Custom resistance band & bodyweight loading",
      "Balance board and stability drills",
      "Core & kinetic chain integration",
      "Graduated home-exercise progression",
    ],
  },
  {
    id: "posture-correction",
    title: "Posture Correction & Ergonomics",
    category: "Spine Care",
    tag: "Lifestyle & Spine",
    shortDesc: "Postural evaluation, ergonomic workstation adjustments, and muscle balancing for modern sedentary lifestyles.",
    fullDesc: "We assess postural compensations, stretch tight anterior muscle chains, and strengthen posterior spinal stabilizers to eliminate desk-related aches and postural fatigue.",
    image: IMAGES?.treatments?.postureCorrection?.src || "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.postureCorrection?.alt || "Postural assessment and spinal alignment",
    conditions: [
      "Forward head & rounded shoulders",
      "Upper crossed & lower crossed syndromes",
      "Desk job-related spinal stiffness",
      "Postural alignment imbalances",
    ],
    approaches: [
      "Postural alignment evaluation",
      "Chest & hip flexor lengthening",
      "Rhomboid & deep neck flexor strengthening",
      "Workplace ergonomic guidance",
    ],
  },
  {
    id: "geriatric-care",
    title: "Geriatric Mobility & Balance Care",
    category: "Senior Care",
    tag: "Gentle Care",
    shortDesc: "Gentle physical therapy dedicated to elderly balance, joint flexibility, fall prevention, and mobility.",
    fullDesc: "Helping senior individuals maintain active independence, walking confidence, and safety at home through gentle, low-impact exercise therapy and joint mobility maintenance.",
    image: IMAGES?.treatments?.geriatricCare?.src || "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=800&q=85",
    alt: IMAGES?.treatments?.geriatricCare?.alt || "Gentle physical therapy for senior mobility",
    conditions: [
      "Age-related balance instability & fall risks",
      "Generalized osteoarthritis & stiffness",
      "Reduced walking endurance",
      "Osteoporosis & posture changes",
    ],
    approaches: [
      "Static & dynamic balance retraining",
      "Safe sit-to-stand & stair mobility training",
      "Gentle joint flexibility maintenance",
      "Assistive device & gait coaching",
    ],
  },
];
